- hosts: "{{ server_name }}"
  gather_facts: no
  vars:
    my_branch: "{{ branchi }}"
    serveruser: "{{ server_user }}"

  tasks:
    - name: Auto Pull
      ansible.builtin.command:
        docker compose pull
      args:
        chdir: /home/{{server_user}}/{{branchi}}
